### ISSUE TITLE
Падает сборка. Тест не проходит по неизвестным причинамю

### ISSUE THREAD

**Issue by KsuxaPoshekhova** [KsuxaPoshekhova/Patterns1#1]
#Описание 
Тест написан корректно, по разборному видео. Но тест падет.

#Локация дефекта
https://github.com/KsuxaPoshekhova/Patterns1/actions/runs/8322938142/job/22771595852#step:6:498

#Шаги воспроизведения

1. Зашла в IDEA , создала Новый проект "[Patterns1](https://github.com/KsuxaPoshekhova/Patterns1)" 
2. Добавила зависимости 

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.0'
    testImplementation 'com.codeborne:selenide:6.17.2'
    testImplementation 'com.github.javafaker:javafaker:1.0.2'

    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    testCompileOnly 'org.projectlombok:lombok:1.18.30'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'
    testImplementation 'org.slf4j:slf4j-simple:2.0.3'
}

test {
    useJUnitPlatform()
    systemProperty 'selenide.headless' , System.getProperty('selenide.headless')

}
3. Создала класс "[DataGenerator.java](https://github.com/KsuxaPoshekhova/Patterns1/blob/main/src/test/java/data/DataGenerator.java)"
4. Создала "package data"
5. Создала класс "[CardDeliveryTest.java](https://github.com/KsuxaPoshekhova/Patterns1/blob/main/src/test/java/ru/netology/CardDeliveryTest.java)"
6. Создала "package ru.netology"
7. Запустила JAR файл ,командой : java -jar ./artifacts/app-replan-delivery.jar
8. Jar файл запущен.
9. Списала тест ,запустила.

*Ожидаемый результат:* Тест запустился ,прошёл успешно. Всё отработано корректно.
*Фактический результат:* Тест запустился ,окно Открылось ,Анкета заполнилась  на половине теста, но  когда нужно было ПЕРЕНАСТРОИТЬ ДАТУ встречи ,всё сломалось и вывелась"BUILD FAILED "

#Окружение
* **Тип системы:**  64-разрядная операционная система, процессор x64
* **IDEA:** "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.4\bin\idea64.exe"
* **JAVA:** OpenJDK11U-jdk_x64_windows_hotspot_11.0.22_7.msi

**Comment by andrew-pahomov** [comment]
Покажите скрины терминала с запущенным джарником

**Comment by andrew-pahomov** [comment]
Покажите логи автотеста на скринах

**Comment by KsuxaPoshekhova** [comment]
скриншот запущенного jar ника

![CardDeliveryTest java –jar файл gradle yml  Patterns1  202](https://github.com/KsuxaPoshekhova/Patterns1/assets/147479684/5b0e141e-5f80-4474-82f2-25e9f80dffe4)

Все логи : 


![CardDeliveryTest java –1 CardDeliveryTest java  Pat](https://github.com/KsuxaPoshekhova/Patterns1/assets/147479684/128eea17-5347-4392-8f79-149e299f8d28)
![CardDeliveryTest java –2 CardDeliveryTest java  Pat](https://github.com/KsuxaPoshekhova/Patterns1/assets/147479684/4c9cfd94-3cc2-4171-979e-4ca7097bc8e0)


![CardDeliveryTest java –3 CardDeliveryTest java  Pat](https://github.com/KsuxaPoshekhova/Patterns1/assets/147479684/f3225210-65ec-43ea-aa65-bbb385ce2489)
![CardDeliveryTest java –4 CardDeliveryTest java  Pat](https://github.com/KsuxaPoshekhova/Patterns1/assets/147479684/c0049a67-07a4-4808-881b-e3add302a4d8)
![CardDeliveryTest java – 5CardDeliveryTest java  Pat](https://github.com/KsuxaPoshekhova/Patterns1/assets/147479684/2bf11f07-8b7c-42ef-a7a5-61fd0d7d47eb)
![CardDeliveryTest java –6 CardDeliveryTest java  Pat](https://github.com/KsuxaPoshekhova/Patterns1/assets/147479684/bfa24fc1-83d9-4dee-a791-e4272882c312)

![CardDeliveryTest java –7 CardDeliveryTest java  Pat](https://github.com/KsuxaPoshekhova/Patterns1/assets/147479684/c73bfc38-7815-4d08-ad37-751af2d5d80c)

![CardDeliveryTest java –8 CardDeliveryTest java  Pat](https://github.com/KsuxaPoshekhova/Patterns1/assets/147479684/cde0e81c-94e5-42ed-8836-91330c0883e4)

![CardDeliveryTest java –9 CardDeliveryTest java  Pat](https://github.com/KsuxaPoshekhova/Patterns1/assets/147479684/46b883ca-e49c-486c-b344-978d2c0701c8)

Сам тест : 
![CardDeliveryTest java – 10 CardDeliveryTest java  Pat](https://github.com/KsuxaPoshekhova/Patterns1/assets/147479684/006c6d45-a1fa-4b18-b91e-eb6792ad4fea)
